# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pp_test_pb2 as pp__test__pb2


class TestServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OnMessageReceived = channel.unary_unary(
        '/test.TestService/OnMessageReceived',
        request_serializer=pp__test__pb2.ReceivedMessage.SerializeToString,
        response_deserializer=pp__test__pb2.Response.FromString,
        )


class TestServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OnMessageReceived(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OnMessageReceived': grpc.unary_unary_rpc_method_handler(
          servicer.OnMessageReceived,
          request_deserializer=pp__test__pb2.ReceivedMessage.FromString,
          response_serializer=pp__test__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test.TestService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
